# Generated by Django 4.2.10 on 2024-03-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_picture', models.ImageField(upload_to='web_picture')),
            ],
        ),
    ]
