# Generated by Django 4.2.10 on 2024-03-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0002_webpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouseldescription',
            name='header',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carouseldescription',
            name='paragraph',
            field=models.CharField(max_length=60),
        ),
    ]
