# Generated by Django 4.2.10 on 2024-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0003_alter_carouseldescription_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouseldescription',
            name='header',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carouseldescription',
            name='paragraph',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
