# Generated by Django 4.2.11 on 2024-04-01 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0004_alter_carouseldescription_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=700)),
                ('work_image', models.ImageField(upload_to='logo/my_work')),
                ('web_logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logo.weblogo')),
            ],
            options={
                'verbose_name_plural': 'About Me',
            },
        ),
    ]
