# Generated by Django 4.2.11 on 2024-04-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0005_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='web_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logo.weblogo'),
        ),
    ]
