# Generated by Django 4.2.11 on 2024-04-02 20:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0006_alter_aboutme_web_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='work_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='carousel',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='weblogo',
            name='web_logo',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='webpicture',
            name='web_picture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
